In [1]:
import numpy as np
import pandas as pd

In [13]:
vk = pd.read_csv('kohli_ipl.csv',index_col='match_no')
vk

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [4]:
subs = pd.read_csv()

In [5]:
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [14]:
movie = pd.read_csv('bollywood.csv',index_col='movie')
movie

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [7]:
## Some important series Methods

In [8]:
# 1> astype   --> to change data type 
import sys
sys.getsizeof(vk)

3472

In [9]:
sys.getsizeof(vk.astype('int16'))

2182

In [11]:
# 2> between 
vk[vk.between(51,99)].size

AttributeError: 'DataFrame' object has no attribute 'between'

In [15]:
# 3> clip

subs.clip(100,200)

     Subscribers gained
0                   100
1                   100
2                   100
3                   100
4                   100
..                  ...
360                 200
361                 200
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [16]:
# 4> drop_duplicates

temp = pd.series([1,1,2,2,3,3,4,4])
temp

AttributeError: module 'pandas' has no attribute 'series'